[package]
name = "bors-demo"
version = "0.1.0"
authors = ["Nick Mosher <nicholastmosher@gmail.com>"]
edition = "2018"

[lib]
name = "bors_demo"
path = "src/lib.rs"

[[bin]]
name = "bors-demo"
path = "src/bin/main.rs"

[dependencies]
